FROM docker.io/library/rockylinux:9

RUN dnf -y install \
        bash \
        findutils \
        gcc \
        git \
        libgomp \
        make \
        python3 \
        python3-pip \
        util-linux \
    && dnf clean all \
    && python3 -m pip install --no-cache-dir "huggingface_hub[cli]<1"

WORKDIR /work/c

ENV MODEL_DIR=/model \
    ARCH=ivybridge \
    RAM_GB=48 \
    NGEN=32 \
    BENCH_LIMIT=10

CMD ["bash", "-lc", "make quickstart ARGS='-y --dir /model --arch ivybridge --ram 48'"]
